In [4]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
reshaped = arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
-flattened =reshaped.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flattened = reshaped.flatten()
flattened[0]=99
flattened

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
raveled=reshaped.ravel()
raveled[1]=88
raveled

array([ 1, 88,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
reshaped

array([[ 1, 88,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([2,3,4])
print(arr2)

[1 2 3]
[2 3 4]


In [14]:
arr1+arr2

array([3, 5, 7])

In [15]:
arr1+4

array([5, 6, 7])

In [5]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[2],[3],[4]])
print(arr2)

[1 2 3]
[[2]
 [3]
 [4]]


In [6]:
arr1+arr2

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])